name: Android Build (Capacitor)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps & sync Android
        run: |
          npm ci || npm i
          npx cap sync android     # <-- generates capacitor-cordova-android-plugins

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v3

      - name: Prepare Gradle wrapper
        working-directory: android
        run: |
          sed -i 's/\r$//' gradlew
          chmod +x gradlew

      - name: Build APK & AAB
        working-directory: android
        run: |
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: android-builds
          path: |
            android/app/build/outputs/apk/release/*.apk
            android/app/build/outputs/bundle/release/*.aab
